{
    "<%= nameUpper %>.general": "General",
    "<%= nameUpper %>.basicInfo": "Basic info",
    "<%= nameUpper %>.add": "Add partner group",
    "<%= nameUpper %>.update": "Update partner group",
    "<%= nameUpper %>.description": "Description",
    "<%= nameUpper %>.name": "Partner group name",
    "<%= nameUpper %>.view": "Partner group details",
    "<%= nameUpper %>.code": "Code",
    "<%= nameUpper %>.action": "Action",
    "<%= nameUpper %>.creator": "Creator",
    "<%= nameUpper %>.markerDate": "Maker date",
    "<%= nameUpper %>.status": "Status",
    "<%= nameUpper %>.active": "Active",
    "<%= nameUpper %>.active.confirmMessage": "Are you sure you want to active this item?",
    "<%= nameUpper %>.deactive": "Deactive",
    "<%= nameUpper %>.deactive.confirmMessage": "Are you sure you want to deactive this item?",
    "<%= nameUpper %>.isExist": "Code is already existed",
    "<%= nameUpper %>.requiredCode": "Please enter partner group code",
    "<%= nameUpper %>.requiredName": "Please enter partner group name"
}